name: ChatManager
main: net.betterverse.chatmanager.ChatManager
version: 1.0
author: aPunch
depend: [PermissionsEx]
commands:
  modchat:
    description: Toggle the private moderator channel
  mute:
    description: Mute a player
  reply:
    description: Reply to a player's private message
    aliases: [r]
  unmute:
    description: Unmute a player
  whisper:
    description: Send a private message to a player
    aliases: [msg, w]
permissions:
  chatmanager.*:
    default: op
    children:
      chatmanager.colored: true
      chatmanager.moderate.*:
        children:
          chatmanager.moderate.modchat: true
          chatmanager.moderate.mute: true
      chatmanager.whisper: true