name: ChatManager
main: net.betterverse.chatmanager.ChatManager
version: 1.0
author: aPunch
depend: [CreditsShop, PermissionsEx]
commands:
  alias:
    description: Set your nickname
  chat:
    description: Various chat-related commands
  ignore:
    description: Ignore a player
  me:
    description: Say what you are doing
  modchat:
    description: Toggle the private moderator channel
  mute:
    description: Mute a player
  prefix:
    description: Set your chat prefix
  reply:
    description: Reply to a player's private message
    aliases: [r]
  unignore:
    description: Unignore a player
  unmute:
    description: Unmute a player
  whisper:
    description: Send a private message to a player
    aliases: [msg, w, tell]
permissions:
  chatmanager.*:
    default: op
    children:
      chatmanager.alias: true
      chatmanager.colored: true
      chatmanager.moderate.*:
        children:
          chatmanager.moderate.alias: true
          chatmanager.moderate.modchat: true
          chatmanager.moderate.mute: true
      chatmanager.whisper: true